name: build
run-name: Build
on:
  push:
    branches: [master]
jobs:
  increase-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set new version
        run: echo VERSION=$(./scripts/increase-version.sh) >> $GITHUB_ENV
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.VERSION }}

  build:
    needs: [increase-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2
      - name: install xelatex and dependencies
        run: |
          sudo apt-get install inkscape texlive-xetex texlive-lang-portuguese
          xelatex --version
      - name: install project fonts
        run: |
          ./scripts/install-font.sh "Gentium Book Plus" "EB Garamond"
      - name: build project
        run: make
