name: build
run-name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2
      - name: install xelatex and dependencies
        run: |
          sudo apt-get install inkscape texlive-xetex texlive-lang-portuguese
          xelatex --version
      - name: install project fonts
        run: |
          ./install-font.sh "Gentium Book Plus" "EB Garamond"
      - name: build project
        run: make
