name: build
run-name: Build
on:
  push:
    branches: [master]
jobs:
  increase-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}

  build:
    needs: [increase-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teatimeguest/setup-texlive-action@v2
      - name: install xelatex and dependencies
        run: |
          sudo apt-get install inkscape texlive-xetex texlive-lang-portuguese
          xelatex --version
      - name: install project fonts
        run: |
          ./scripts/install-font.sh "Gentium Book Plus" "EB Garamond"
      - name: build project
        run: make
